# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: NuGet package publish

on:
  push:
    branches: [ "main" ]

jobs:
  build-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Resore dependencies
      run: dotnet restore BroLake.Cloudflare.Identity.csproj
    - name: Build
      run: dotnet build --no-restore BroLake.Cloudflare.Identity.csproj
    - name: Pack
      run: dotnet pack BroLake.Cloudflare.Identity.csproj -c Release
    - name: Prepare GitHub packages
      run: dotnet nuget add source --username alexmarian99 --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/brolakehub/index.json"
    - name: Publish to GitHub packages
      run: dotnet nuget push bin/Release/*.nupkg --api-key ${{secrets.GITHUB_TOKEN}} --source "github"
